Repository CSCfi/swift-browser-ui, pull requests merged in 2020-04, with the labels that each got.

#72 Hotfix/q1 npm audit – Bump vue @v3.12.1 -> @v4.3.0
  swift_browser_ui_frontend/babel.config.js
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
Labels: enhancement

#71 Feature/implement uploads
  swift_browser_ui/_convenience.py
  swift_browser_ui/api.py
  swift_browser_ui/login.py
  swift_browser_ui/server.py
  swift_browser_ui/settings.py
  swift_browser_ui/signature.py
  swift_browser_ui_frontend/babel.config.js
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/src/common/api.js
  swift_browser_ui_frontend/src/common/conv.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/common/router.js
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/components/ACLDiscover.vue
  swift_browser_ui_frontend/src/components/Breadcrumb.vue
  swift_browser_ui_frontend/src/components/BrowserNavbar.vue
  swift_browser_ui_frontend/src/components/ContainerDownloadLink.vue
  swift_browser_ui_frontend/src/components/FolderUpload.vue
  swift_browser_ui_frontend/src/components/ReplicateContainer.vue
  swift_browser_ui_frontend/src/components/RequestSharing.vue
  swift_browser_ui_frontend/src/components/ShareRequestsTable.vue
  swift_browser_ui_frontend/src/components/SharedDetails.vue
  swift_browser_ui_frontend/src/components/SharedMenu.vue
  swift_browser_ui_frontend/src/components/SharedOutTable.vue
  swift_browser_ui_frontend/src/components/SharedTable.vue
  swift_browser_ui_frontend/src/components/UploadProgressBar.vue
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/pages/Browser.vue
  swift_browser_ui_frontend/src/views/Containers.vue
  swift_browser_ui_frontend/src/views/DirectRequest.vue
  swift_browser_ui_frontend/src/views/Objects.vue
  swift_browser_ui_frontend/src/views/Replicate.vue
  swift_browser_ui_frontend/src/views/SharedObjects.vue
  swift_browser_ui_frontend/src/views/Sharing.vue
  tests/ui/test_frontend_chrome.py
  tests/ui/test_frontend_firefox.py
  tests/unit/test_api.py
Labels: bug, enhancement

#73 Merge v1.0.0rc1
  Dockerfile
  docs/source/conf.py
  swift_browser_ui/__init__.py
  swift_browser_ui/_convenience.py
  swift_browser_ui/api.py
  swift_browser_ui/login.py
  swift_browser_ui/server.py
  swift_browser_ui/settings.py
  swift_browser_ui/signature.py
  swift_browser_ui_frontend/babel.config.js
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/src/common/api.js
  swift_browser_ui_frontend/src/common/conv.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/common/router.js
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/components/ACLDiscover.vue
  swift_browser_ui_frontend/src/components/Breadcrumb.vue
  swift_browser_ui_frontend/src/components/BrowserNavbar.vue
  swift_browser_ui_frontend/src/components/ContainerDownloadLink.vue
  swift_browser_ui_frontend/src/components/FolderUpload.vue
  swift_browser_ui_frontend/src/components/ReplicateContainer.vue
  swift_browser_ui_frontend/src/components/RequestSharing.vue
  swift_browser_ui_frontend/src/components/ShareRequestsTable.vue
  swift_browser_ui_frontend/src/components/SharedDetails.vue
  swift_browser_ui_frontend/src/components/SharedMenu.vue
  swift_browser_ui_frontend/src/components/SharedOutTable.vue
  swift_browser_ui_frontend/src/components/SharedTable.vue
  swift_browser_ui_frontend/src/components/UploadProgressBar.vue
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/pages/Browser.vue
  swift_browser_ui_frontend/src/views/Containers.vue
  swift_browser_ui_frontend/src/views/DirectRequest.vue
  swift_browser_ui_frontend/src/views/Objects.vue
  swift_browser_ui_frontend/src/views/Replicate.vue
  swift_browser_ui_frontend/src/views/SharedObjects.vue
  swift_browser_ui_frontend/src/views/Sharing.vue
  tests/ui/test_frontend_chrome.py
  tests/ui/test_frontend_firefox.py
  tests/unit/test_api.py
Labels: bug, enhancement

#74 Documentation/v1.0.0 rc1 doc update
  docs/source/_static/images/container-share-view.png
  docs/source/_static/images/replication-view.png
  docs/source/_static/images/screenshot-dashboard
  docs/source/_static/images/screenshot-front-page
  docs/source/_static/images/screenshot-login-page
  docs/source/_static/images/screenshot-object-details
  docs/source/_static/images/screenshot-object-page
  docs/source/_static/images/shared-out-view.png
  docs/source/_static/images/shared-to-view.png
  docs/source/_static/images/sharing-request-view.png
  docs/source/code.rst
  docs/source/deploy.rst
  docs/source/index.rst
  docs/source/instructions.rst
  docs/source/request.rst
  docs/source/runner.rst
  docs/source/sharing.rst
Labels: documentation

#76 Calculate BU close to zero
  swift_browser_ui_frontend/src/common/api.js
  swift_browser_ui_frontend/src/components/FolderUpload.vue
Labels: bug

#75 Reposition buttons
  swift_browser_ui_frontend/src/pages/Browser.vue
  swift_browser_ui_frontend/src/views/Containers.vue
  swift_browser_ui_frontend/src/views/Objects.vue
  swift_browser_ui_frontend/src/views/SharedObjects.vue
  swift_browser_ui_frontend/src/views/Sharing.vue
Labels: bug, enhancement
