Repository CSCfi/swift-browser-ui, pull requests merged in 2021-05, with the labels that each got.

#189 fix and update dependencies
  setup.py
Labels: bug, dependencies

#190 Feature/containe object addition deletion
  swift_browser_ui/api.py
  swift_browser_ui/server.py
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/src/common/api.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/common/router.js
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/components/ContainerDeleteButton.vue
  swift_browser_ui_frontend/src/components/ObjectDeleteButton.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
  swift_browser_ui_frontend/src/pages/Browser.vue
  swift_browser_ui_frontend/src/views/AddContainer.vue
  swift_browser_ui_frontend/src/views/Containers.vue
  swift_browser_ui_frontend/src/views/DirectRequest.vue
  tests/ui/common.py
Labels: enhancement

#210 Feature/direct share create
  swift_browser_ui/api.py
  swift_browser_ui_frontend/src/common/router.js
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/components/ObjectTable.vue
  swift_browser_ui_frontend/src/views/DirectRequest.vue
  swift_browser_ui_frontend/src/views/DirectShare.vue
Labels: bug, enhancement

#211 Update/aggregate dependabot bumps
  requirements.txt
  setup.py
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
Labels: dependencies

#213 fix incorrect router call
  swift_browser_ui_frontend/src/views/DirectShare.vue
Labels: bug

#221 Update/packages npm and pip
  Dockerfile
  Dockerfile-Devel
  Dockerfile-SD
  requirements.txt
  setup.py
  sftp_ui.py
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
Labels: dependencies
