Repository CSCfi/swift-browser-ui, pull requests merged in 2021-06, with the labels that each got.

#239 Update/packages jun14
  Dockerfile
  Dockerfile-Devel
  Dockerfile-SD
  setup.py
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
  tox.ini
Labels: bug, dependencies

#241 change naming from containers to buckets
  swift_browser_ui_frontend/src/common/lang.js
Labels: enhancement

#243 change upload chunk size
  swift_browser_ui/api.py
  swift_browser_ui_frontend/src/entries/main.js
Labels: bug

#245 Merge v1.1.0b2
  Dockerfile
  Dockerfile-Devel
  Dockerfile-SD
  docs/source/conf.py
  requirements.txt
  setup.py
  swift_browser_ui/__init__.py
  swift_browser_ui/api.py
  swift_browser_ui_frontend/config/images/favicon-csc.ico
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/entries/main.js
  tox.ini
Labels: bug, dependencies, enhancement

#254 update packages
  setup.py
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
Labels: dependencies

#253 Fix UI information overrides
  swift_browser_ui_frontend/config/sd_overrides.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/views/Dashboard.vue
Labels: enhancement

#256 Feature/add help button
  swift_browser_ui_frontend/config/sd_overrides.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/components/BrowserNavbar.vue
Labels: enhancement
