Repository CSCfi/swift-browser-ui, pull requests merged in 2021-11, with the labels that each got.

#393 typo: Containers -> ContainersView
  swift_browser_ui_frontend/src/entries/main.js
Labels: bug

#409 Add support for Openstak Fernet tokens
  swift_browser_ui/ui/login.py
Labels: enhancement

#410 Docs/update api docs
  README.md
  docs/API_spec.yml
  docs/_static/api.yml
  docs/_static/sharing_api.yml
  docs/source/_static/api.yml
  docs/source/tech.rst
  docs/source/testing.rst
Labels: documentation
