Repository CSCfi/swift-browser-ui, pull requests merged in 2021-12, with the labels that each got.

#411 v1.1.0b7
  .github/dependabot.yml
  .github/workflows/e2etests.yml
  .github/workflows/eslint.yml
  .github/workflows/style.yml
  .github/workflows/unit.yml
  README.md
  dockerfiles/Dockerfile-ui
  dockerfiles/Dockerfile-ui-devel
  docs/API_spec.yml
  docs/_static/api.yml
  docs/_static/sharing_api.yml
  docs/source/_static/api.yml
  docs/source/conf.py
  docs/source/tech.rst
  docs/source/testing.rst
  requirements.txt
  setup.py
  swift_browser_ui/ui/api.py
  swift_browser_ui/ui/login.py
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/src/common/router.js
  swift_browser_ui_frontend/src/components/Breadcrumb.vue
  swift_browser_ui_frontend/src/components/BrowserNavbar.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
  swift_browser_ui_frontend/src/components/SharedOutTable.vue
  swift_browser_ui_frontend/src/components/Sharing.vue
  swift_browser_ui_frontend/src/entries/badrequest.js
  swift_browser_ui_frontend/src/entries/forbid.js
  swift_browser_ui_frontend/src/entries/index.js
  swift_browser_ui_frontend/src/entries/login.js
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/entries/notfound.js
  swift_browser_ui_frontend/src/entries/uidown.js
  swift_browser_ui_frontend/src/entries/unauth.js
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/pages/IndexPage.vue
  swift_browser_ui_frontend/src/pages/LoginPage.vue
  swift_browser_ui_frontend/src/views/Containers.vue
  swift_browser_ui_frontend/src/views/Dashboard.vue
  swift_browser_ui_frontend/src/views/Objects.vue
  swift_browser_ui_frontend/src/views/Shared.vue
  swift_browser_ui_frontend/src/views/SharedObjects.vue
  swift_browser_ui_frontend/src/views/Sharing.vue
  swift_browser_ui_frontend/src/views/Tokens.vue
  tests/ui_unit/test_api.py
Labels: release

#419 Allow a person to tag buckets.
  docs/_static/api.yml
  swift_browser_ui/ui/api.py
  swift_browser_ui/ui/server.py
  swift_browser_ui_frontend/src/common/api.js
  swift_browser_ui_frontend/src/common/conv.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/common/router.js
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/components/ContainerDeleteButton.vue
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/views/AddContainer.vue
  swift_browser_ui_frontend/src/views/Containers.vue
  swift_browser_ui_frontend/src/views/Replicate.vue
  tests/common/mockups.py
  tests/cypress/integration/browser.spec.js
  tests/ui_unit/test_api.py
Labels: enhancement

#422 Automatically refresh ACL information in sharing db
  swift_browser_ui/ui/api.py
  swift_browser_ui_frontend/src/common/api.js
  swift_browser_ui_frontend/src/common/conv.js
  swift_browser_ui_frontend/src/components/ACLDiscover.vue
  swift_browser_ui_frontend/src/entries/main.js
Labels: enhancement

#443 Fix buefy broken link to docs.
  docs/source/index.rst
Labels: bug
