Repository CSCfi/swift-browser-ui, pull requests merged in 2022-02, with the labels that each got.

#489 fix: container download link after page refresh
  swift_browser_ui_frontend/src/components/ContainerDownloadLink.vue
Labels: bug

#491 Error catching and hiding
  CHANGELOG.md
  swift_browser_ui_frontend/.eslintrc.json
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/src/common/api.js
  swift_browser_ui_frontend/src/common/conv.js
  swift_browser_ui_frontend/src/common/swift_sharing_request_bind.js
  swift_browser_ui_frontend/src/common/swift_x_account_sharing_bind.js
  swift_browser_ui_frontend/src/entries/main.js
Labels: debt

#493 Feature/new upload UI
  .github/config/.finnishwords.txt
  .github/config/.wordlist.txt
  CHANGELOG.md
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/public/index.html
  swift_browser_ui_frontend/src/common/conv.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/components/BrowserNavbar.vue
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/views/AddContainer.vue
  swift_browser_ui_frontend/src/views/EditObject.vue
  swift_browser_ui_frontend/src/views/Replicate.vue
  swift_browser_ui_frontend/src/views/Sharing.vue
  swift_browser_ui_frontend/src/views/Tokens.vue
  swift_browser_ui_frontend/src/views/Upload.vue
  swift_browser_ui_frontend/vue.config.js
Labels: bug, enhancement

#497 Bugfix/drag drop fixes
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/views/Upload.vue
Labels: bug

#498 properly clean dropitemlist
  .github/config/.finnishwords.txt
  CHANGELOG.md
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/public/index.html
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/views/Upload.vue
Labels: bug

#503 bulk updates feb 11 2022
  CHANGELOG.md
  dockerfiles/Dockerfile-build-crypt
  dockerfiles/Dockerfile-build-crypt-devel
  dockerfiles/Dockerfile-ui
  dockerfiles/Dockerfile-ui-devel
  requirements.txt
  setup.py
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
Labels: npm dependencies, docker dependencies, pip dependencies

#506 Search improvements
  .github/config/.finnishwords.txt
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/conv.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/components/ObjectTable.vue
  swift_browser_ui_frontend/src/components/SearchResultItem.vue
  swift_browser_ui_frontend/src/views/AddContainer.vue
  swift_browser_ui_frontend/src/views/Containers.vue
Labels: enhancement

#511 reduce login.py log visibility in debug mode
  swift_browser_ui/ui/login.py
Labels: bug

#512 Bugfix/fix availability check comparison
  swift_browser_ui/ui/_convenience.py
  swift_browser_ui/ui/front.py
  swift_browser_ui/ui/login.py
  tests/ui_unit/test_login.py
Labels: bug, debt

#513 use redis cookie storage
  CHANGELOG.md
  requirements.txt
  setup.py
  swift_browser_ui/ui/server.py
Labels: enhancement, dependencies, debt

#515 Docs/UI api v2
  CHANGELOG.md
  docs/_static/api.yml
Labels: documentation, debt

#518 Fix editing object tags
  swift_browser_ui_frontend/src/views/EditObject.vue
Labels: bug

#520 Fix getting object metadata for large containers.
  swift_browser_ui_frontend/src/common/store.js
Labels: bug

#521 invalidate expired sessions
  swift_browser_ui/ui/_convenience.py
  swift_browser_ui/ui/front.py
  swift_browser_ui/ui/middlewares.py
  swift_browser_ui/ui/server.py
  tests/common/mockups.py
  tests/ui_unit/test_middlewares.py
Labels: enhancement
