Repository CSCfi/swift-browser-ui, pull requests merged in 2022-10, with the labels that each got.

#746 Feature/new data table layout
  .github/config/.finnishwords.txt
  CHANGELOG.md
  package-lock.json
  package.json
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/src/common/conv.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/common/router.js
  swift_browser_ui_frontend/src/components/BrowserSecondaryNavbar.vue
  swift_browser_ui_frontend/src/components/CObjectTable.vue
  swift_browser_ui_frontend/src/components/ContainerTable.vue
  swift_browser_ui_frontend/src/components/FolderTabs.vue
  swift_browser_ui_frontend/src/components/ObjectDeleteButton.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
  swift_browser_ui_frontend/src/components/SearchBox.vue
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/views/Containers.vue
  swift_browser_ui_frontend/src/views/Folders.vue
  swift_browser_ui_frontend/src/views/Objects.vue
Labels: enhancement

#714 Feature/share modal
  .github/config/.finnishwords.txt
  .github/config/.wordlist.txt
  CHANGELOG.md
  package-lock.json
  package.json
  swift_browser_ui/common/common_handlers.py
  swift_browser_ui/sharing/server.py
  swift_browser_ui_frontend/src/common/api.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/common/router.js
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/common/swift_x_account_sharing_bind.js
  swift_browser_ui_frontend/src/components/ContainerTable.vue
  swift_browser_ui_frontend/src/components/ShareModal.vue
  swift_browser_ui_frontend/src/components/ShareModalTable.vue
  swift_browser_ui_frontend/src/components/SharedMenu.vue
  swift_browser_ui_frontend/src/components/SharedOutTable.vue
  swift_browser_ui_frontend/src/views/Containers.vue
  swift_browser_ui_frontend/src/views/Folders.vue
  swift_browser_ui_frontend/src/views/Shared.vue
  swift_browser_ui_frontend/src/views/Sharing.vue
Labels: enhancement

#748 Feature/edit tags
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/globalFunctions.js
  swift_browser_ui_frontend/src/common/router.js
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/components/CObjectTable.vue
  swift_browser_ui_frontend/src/components/ContainerTable.vue
  swift_browser_ui_frontend/src/components/EditTagsModal.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/views/Containers.vue
  swift_browser_ui_frontend/src/views/EditObject.vue
Labels: enhancement

#751 Feature/copy modal
  .github/config/.finnishwords.txt
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/api.js
  swift_browser_ui_frontend/src/common/globalFunctions.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/common/router.js
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/components/ContainerTable.vue
  swift_browser_ui_frontend/src/components/Containers.vue
  swift_browser_ui_frontend/src/components/CopyFolderModal.vue
  swift_browser_ui_frontend/src/components/FolderOptionsMenu.vue
  swift_browser_ui_frontend/src/components/ReplicateContainer.vue
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/views/Replicate.vue
Labels: enhancement

#788 Fix for showing tags of objects inside a copied folder
  CHANGELOG.md
  swift_browser_ui/upload/replicate.py
  swift_browser_ui_frontend/src/components/Containers.vue
Labels: bug

#741 Use correct URL parameter for API token requests
  .github/config/.finnishwords.txt
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/views/Tokens.vue
  swift_browser_ui_frontend/vue.config.js
Labels: bug

#600 docker with OIDC does need permission in app/
  dockerfiles/Dockerfile-build-crypt
  dockerfiles/Dockerfile-build-crypt-devel
  dockerfiles/Dockerfile-ui
  dockerfiles/Dockerfile-ui-devel
Labels: bug, debt
