Repository CSCfi/swift-browser-ui, pull requests merged in 2022-01, with the labels that each got.

#444 use pyspelling as spellchecker
  .github/config/.finnishwords.txt
  .github/config/.spellcheck.yml
  .github/config/.wordlist.txt
  .github/workflows/spellcheck.yml
  .gitignore
  README-sharing.md
  README.md
  docs/source/runner.rst
  docs/source/sharing.rst
  docs/source/tools.rst
  docs/source/ui.rst
  swift_browser_ui_frontend/src/common/lang.js
Labels: enhancement, github actions

#395 Upload encryption with WASM
  dockerfiles/Dockerfile-build-crypt
  dockerfiles/Dockerfile-build-crypt-devel
  dockerfiles/Dockerfile-ui-devel
  swift_browser_ui/ui/api.py
  swift_browser_ui/ui/server.py
  swift_browser_ui/upload/api.py
  swift_browser_ui_frontend/public/index.html
  swift_browser_ui_frontend/src/common/api.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/common/router.js
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/components/FolderUpload.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
  swift_browser_ui_frontend/src/components/UploadButton.vue
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/views/Containers.vue
  swift_browser_ui_frontend/src/views/Upload.vue
  swift_browser_ui_frontend/wasm/Makefile
  swift_browser_ui_frontend/wasm/README.md
  swift_browser_ui_frontend/wasm/src/include/upinit.h
  swift_browser_ui_frontend/wasm/src/include/upload.h
  swift_browser_ui_frontend/wasm/src/include/uptypes.h
  swift_browser_ui_frontend/wasm/src/upinit.c
  swift_browser_ui_frontend/wasm/src/upload.c
  tests/ui_unit/test_api.py
Labels: enhancement

#473 check container in upload to prevent error
  swift_browser_ui_frontend/src/views/Upload.vue
Labels: bug

#476 Bugfix/cors headers
  .github/workflows/e2etests.yml
  .github/workflows/eslint.yml
  .github/workflows/unit.yml
  CHANGELOG.md
  dockerfiles/Dockerfile-build-crypt
  dockerfiles/Dockerfile-build-crypt-devel
  dockerfiles/Dockerfile-ui
  dockerfiles/Dockerfile-ui-devel
  swift_browser_ui/common/common_middleware.py
  swift_browser_ui/upload/upload.py
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/views/AddContainer.vue
  swift_browser_ui_frontend/src/views/Upload.vue
Labels: bug
