Repository CSCfi/swift-browser-ui, pull requests merged in 2022-11, with the labels that each got.

#825 Fix Python unit and style tests
  swift_browser_ui/upload/download.py
  tests/sharing/test_db.py
  tox.ini
Labels: bug, debt

#829 Update/package versions 11 2022
  .github/workflows/docs.yml
  .github/workflows/spellcheck.yml
  .github/workflows/style.yml
  .github/workflows/unit.yml
  .github/workflows/vueunit.yml
  CHANGELOG.md
  dockerfiles/Dockerfile-build-crypt
  dockerfiles/Dockerfile-build-crypt-devel
  dockerfiles/Dockerfile-ui
  dockerfiles/Dockerfile-ui-devel
  requirements.txt
  setup.py
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/src/components/Containers.vue
  swift_browser_ui_frontend/src/components/CopyFolderModal.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
Labels: dependencies, debt

#853 Install python for Node 18
  CHANGELOG.md
  dockerfiles/Dockerfile-build-crypt
  dockerfiles/Dockerfile-build-crypt-devel
  dockerfiles/Dockerfile-ui
  dockerfiles/Dockerfile-ui-devel
Labels: bug

#850 refresh noupload on file entry
  CHANGELOG.md
  swift_browser_ui_frontend/src/components/UploadModal.vue
Labels: bug
