Repository CSCfi/swift-browser-ui, pull requests merged in 2022-04, with the labels that each got.

#562 package-log.json out of sync for v2.0.1
  swift_browser_ui_frontend/package-lock.json
Labels: bug

#566 Make project change reload the page.
  CHANGELOG.md
  swift_browser_ui/ui/api.py
  swift_browser_ui_frontend/src/components/BrowserNavbar.vue
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/views/Dashboard.vue
  tests/cypress/integration/browser.spec.js
  tests/cypress/integration/userInfo.spec.js
Labels: bug, debt

#567 Prevent unexpected errors in empty projects
  swift_browser_ui/ui/api.py
  swift_browser_ui_frontend/src/views/Dashboard.vue
Labels: bug

#569 Update dev process
  .dockerignore
  .github/config/.env.test
  .github/config/.wordlist.txt
  .github/config/init-project-db.sh
  .github/workflows/e2etests.yml
  .gitignore
  CHANGELOG.md
  Procfile
  README.md
  swift_browser_ui_frontend/cypress.json
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/vue.config.js
Labels: documentation, enhancement, debt
