Repository CSCfi/swift-browser-ui, pull requests merged in 2022-06, with the labels that each got.

#614 Feature/new error pages
  .github/config/.finnishwords.txt
  .github/workflows/e2etests.yml
  CHANGELOG.md
  swift_browser_ui_frontend/.gitignore
  swift_browser_ui_frontend/cypress.config.js
  swift_browser_ui_frontend/cypress.json
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/components/BrowserNavbar.vue
  swift_browser_ui_frontend/src/components/CLanguageSelector.vue
  swift_browser_ui_frontend/src/entries/badrequest.js
  swift_browser_ui_frontend/src/entries/forbid.js
  swift_browser_ui_frontend/src/entries/index.js
  swift_browser_ui_frontend/src/entries/loginpassword.js
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/entries/notfound.js
  swift_browser_ui_frontend/src/entries/uidown.js
  swift_browser_ui_frontend/src/entries/unauth.js
  swift_browser_ui_frontend/src/pages/IndexPage.vue
  swift_browser_ui_frontend/src/pages/LoginPassword.vue
  tests/cypress/integration/browser.cy.js
  tests/cypress/integration/userInfo.cy.js
  tests/cypress/support/commands.js
Labels: enhancement, debt

#646 Update all deps
  .github/workflows/codeql-analysis.yml
  .github/workflows/e2etests.yml
  .github/workflows/publish.yml
  .github/workflows/spellcheck.yml
  dockerfiles/Dockerfile-build-crypt
  dockerfiles/Dockerfile-build-crypt-devel
  dockerfiles/Dockerfile-ui
  dockerfiles/Dockerfile-ui-devel
  requirements.txt
  setup.py
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
Labels: debt

#637 Feature/new navigation layout
  .github/config/.finnishwords.txt
  .github/workflows/e2etests.yml
  CHANGELOG.md
  swift_browser_ui_frontend/jsconfig.json
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/components/BrowserMainNavbar.vue
  swift_browser_ui_frontend/src/components/BrowserNavbar.vue
  swift_browser_ui_frontend/src/components/BrowserSecondaryNavbar.vue
  swift_browser_ui_frontend/src/components/BrowserUserMenu.vue
  swift_browser_ui_frontend/src/components/CLanguageSelector.vue
  swift_browser_ui_frontend/src/css/csc.scss
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/pages/IndexPage.vue
  swift_browser_ui_frontend/src/views/Dashboard.vue
  tests/cypress/integration/browser.cy.js
  tests/cypress/integration/userInfo.cy.js
  tests/cypress/support/commands.js
Labels: enhancement
