Repository CSCfi/swift-browser-ui, pull requests merged in 2023-03, with the labels that each got.

#989 Make selected display options consistent
  CHANGELOG.md
  swift_browser_ui_frontend/src/components/Containers.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
Labels: bug, enhancement

#999 Fix vault instructions
  .github/config/.env.test
  README.md
Labels: bug, debt

#1000 Update dockerfiles to use pyproject.toml
  dockerfiles/Dockerfile-build-crypt
  dockerfiles/Dockerfile-build-crypt-devel
  dockerfiles/Dockerfile-request
  dockerfiles/Dockerfile-runner
  dockerfiles/Dockerfile-sharing
  dockerfiles/Dockerfile-ui
  dockerfiles/Dockerfile-ui-devel
Labels: bug, debt

#1001 Add workflow for updating pnpm packages
  .github/workflows/docs.yml
  .github/workflows/eslint.yml
  .github/workflows/pnpm-autoupdate.yml
  .github/workflows/spellcheck.yml
  .github/workflows/style.yml
  .github/workflows/unit.yml
  .github/workflows/vueunit.yml
Labels: dependencies, debt

#986 Bugfix/small window modal behaviour
  swift_browser_ui_frontend/src/components/CreateFolderModal.vue
Labels: bug, debt

#1007 Replace Buefy Taginput and Taglist component
  .github/config/.finnishwords.txt
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/conv.js
  swift_browser_ui_frontend/src/common/globalFunctions.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/components/CopyFolderModal.vue
  swift_browser_ui_frontend/src/components/CreateFolderModal.vue
  swift_browser_ui_frontend/src/components/EditTagsModal.vue
  swift_browser_ui_frontend/src/components/ShareModal.vue
  swift_browser_ui_frontend/src/components/TagInput.vue
  swift_browser_ui_frontend/src/components/UploadModal.vue
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/views/DirectShare.vue
Labels: enhancement, debt

#1015 Remove unused components and views
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/router.js
  swift_browser_ui_frontend/src/components/ACLDiscover.vue
  swift_browser_ui_frontend/src/components/ContainerDownloadLink.vue
  swift_browser_ui_frontend/src/components/ObjectDeleteButton.vue
  swift_browser_ui_frontend/src/components/ReplicateContainer.vue
  swift_browser_ui_frontend/src/components/RequestSharing.vue
  swift_browser_ui_frontend/src/components/ShareRequestsTable.vue
  swift_browser_ui_frontend/src/components/SharedDetails.vue
  swift_browser_ui_frontend/src/components/SharedMenu.vue
  swift_browser_ui_frontend/src/views/Dashboard.vue
  swift_browser_ui_frontend/src/views/DirectRequest.vue
  swift_browser_ui_frontend/src/views/DirectShare.vue
  swift_browser_ui_frontend/src/views/ShareRequests.vue
  swift_browser_ui_frontend/src/views/SharedFrom.vue
  swift_browser_ui_frontend/src/views/SharedTo.vue
Labels: debt

#1016 Replace buefy components with csc-ui components
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/components/CopyFolderModal.vue
  swift_browser_ui_frontend/src/components/CreateFolderModal.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
  swift_browser_ui_frontend/src/components/SearchBox.vue
  swift_browser_ui_frontend/src/components/UploadModal.vue
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/entries/select.js
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/pages/SelectPage.vue
  swift_browser_ui_frontend/src/views/Tokens.vue
Labels: enhancement, debt

#1017 Small UI changes
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/components/BrowserSecondaryNavbar.vue
  swift_browser_ui_frontend/src/components/CreateFolderModal.vue
Labels: enhancement

#1027 Fix for empty Shared folders
  swift_browser_ui_frontend/src/components/ShareModal.vue
  swift_browser_ui_frontend/src/components/TagInput.vue
Labels: bug

#1029 Try another way to prevent background scrolling to top when a modal is open
  swift_browser_ui_frontend/src/common/globalFunctions.js
  swift_browser_ui_frontend/src/components/BrowserSecondaryNavbar.vue
  swift_browser_ui_frontend/src/components/ContainerTable.vue
  swift_browser_ui_frontend/src/components/CopyFolderModal.vue
  swift_browser_ui_frontend/src/components/CreateFolderModal.vue
  swift_browser_ui_frontend/src/components/DeleteModal.vue
  swift_browser_ui_frontend/src/components/EditTagsModal.vue
  swift_browser_ui_frontend/src/components/ShareModal.vue
  swift_browser_ui_frontend/src/components/UploadModal.vue
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
Labels: enhancement

#1030 Replace b-upload with a new component CUploadButton
  CHANGELOG.md
  swift_browser_ui_frontend/src/components/CUploadButton.vue
  swift_browser_ui_frontend/src/components/UploadModal.vue
Labels: enhancement, debt

#1033 Feature/replace buefy autocomplete
  CHANGELOG.md
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/pnpm-lock.yaml
  swift_browser_ui_frontend/src/components/SearchBox.vue
  swift_browser_ui_frontend/src/components/SearchResultItem.vue
Labels: enhancement, dependencies, debt

#1006 migrate away from buefy
  CHANGELOG.md
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/pnpm-lock.yaml
  swift_browser_ui_frontend/src/components/CUploadButton.vue
  swift_browser_ui_frontend/src/components/FolderTabs.vue
  swift_browser_ui_frontend/src/components/SearchResultItem.vue
  swift_browser_ui_frontend/src/components/TagInput.vue
  swift_browser_ui_frontend/src/css/csc.scss
  swift_browser_ui_frontend/src/css/dark.scss
  swift_browser_ui_frontend/src/css/light.scss
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/entries/select.js
Labels: enhancement, npm dependencies, debt

#982 Migrate from vue-cli to vite
  .github/config/.env.test
  CHANGELOG.md
  Procfile
  devproxy/nginx.conf
  swift_browser_ui_frontend/.eslintrc.json
  swift_browser_ui_frontend/babel.config.js
  swift_browser_ui_frontend/build_wasm.sh
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/pnpm-lock.yaml
  swift_browser_ui_frontend/src/400.html
  swift_browser_ui_frontend/src/401.html
  swift_browser_ui_frontend/src/403.html
  swift_browser_ui_frontend/src/404.html
  swift_browser_ui_frontend/src/503.html
  swift_browser_ui_frontend/src/browse.html
  swift_browser_ui_frontend/src/common/api.js
  swift_browser_ui_frontend/src/common/conv.js
  swift_browser_ui_frontend/src/common/router.js
  swift_browser_ui_frontend/src/components/AllFoldersTable.vue
  swift_browser_ui_frontend/src/components/BrowserMainNavbar.vue
  swift_browser_ui_frontend/src/components/BrowserSecondaryNavbar.vue
  swift_browser_ui_frontend/src/components/CFooter.vue
  swift_browser_ui_frontend/src/components/Containers.vue
  swift_browser_ui_frontend/src/components/CopyFolderModal.vue
  swift_browser_ui_frontend/src/components/CreateFolderModal.vue
  swift_browser_ui_frontend/src/components/EditTagsModal.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
  swift_browser_ui_frontend/src/components/SearchBox.vue
  swift_browser_ui_frontend/src/components/ShareModal.vue
  swift_browser_ui_frontend/src/components/SharedOutTable.vue
  swift_browser_ui_frontend/src/components/SharedTable.vue
  swift_browser_ui_frontend/src/components/UploadAlert.vue
  swift_browser_ui_frontend/src/components/UploadModal.vue
  swift_browser_ui_frontend/src/components/UploadNotification.vue
  swift_browser_ui_frontend/src/components/UploadProgressBar.vue
  swift_browser_ui_frontend/src/components/UploadToast.vue
  swift_browser_ui_frontend/src/css/csc.scss
  swift_browser_ui_frontend/src/css/dark.scss
  swift_browser_ui_frontend/src/css/light.scss
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/index.html
  swift_browser_ui_frontend/src/index_oidc.html
  swift_browser_ui_frontend/src/login.html
  swift_browser_ui_frontend/src/login2step.html
  swift_browser_ui_frontend/src/loginpassword.html
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/select.html
  swift_browser_ui_frontend/src/views/Objects.vue
  swift_browser_ui_frontend/src/views/SharedObjects.vue
  swift_browser_ui_frontend/src/views/Tokens.vue
  swift_browser_ui_frontend/vite.config.js
  swift_browser_ui_frontend/vue.config.js
Labels: debt

#1037 Ignore other commonly used files/folders
  .gitignore
Labels: enhancement

#1034 Migrate to vue3
  CHANGELOG.md
  swift_browser_ui_frontend/.eslintrc.json
  swift_browser_ui_frontend/.gitignore
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/pnpm-lock.yaml
  swift_browser_ui_frontend/src/common/api.js
  swift_browser_ui_frontend/src/common/csc-ui-vue-directive.js
  swift_browser_ui_frontend/src/common/csc-ui.js
  swift_browser_ui_frontend/src/common/db.js
  swift_browser_ui_frontend/src/common/i18n.js
  swift_browser_ui_frontend/src/common/router.js
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/common/upload.js
  swift_browser_ui_frontend/src/components/BrowserMainNavbar.vue
  swift_browser_ui_frontend/src/components/BrowserSecondaryNavbar.vue
  swift_browser_ui_frontend/src/components/CUploadButton.vue
  swift_browser_ui_frontend/src/components/Containers.vue
  swift_browser_ui_frontend/src/components/CopyFolderModal.vue
  swift_browser_ui_frontend/src/components/CreateFolderModal.vue
  swift_browser_ui_frontend/src/components/DeleteModal.vue
  swift_browser_ui_frontend/src/components/EditTagsModal.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
  swift_browser_ui_frontend/src/components/SearchBox.vue
  swift_browser_ui_frontend/src/components/SearchResultItem.vue
  swift_browser_ui_frontend/src/components/ShareModal.vue
  swift_browser_ui_frontend/src/components/UploadModal.vue
  swift_browser_ui_frontend/src/entries/badrequest.js
  swift_browser_ui_frontend/src/entries/forbid.js
  swift_browser_ui_frontend/src/entries/index.js
  swift_browser_ui_frontend/src/entries/index_app_factory.js
  swift_browser_ui_frontend/src/entries/index_oidc.js
  swift_browser_ui_frontend/src/entries/login.js
  swift_browser_ui_frontend/src/entries/loginpassword.js
  swift_browser_ui_frontend/src/entries/main.js
  swift_browser_ui_frontend/src/entries/notfound.js
  swift_browser_ui_frontend/src/entries/select.js
  swift_browser_ui_frontend/src/entries/uidown.js
  swift_browser_ui_frontend/src/entries/unauth.js
  swift_browser_ui_frontend/src/index_oidc.html
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/pages/IndexOIDCPage.vue
  swift_browser_ui_frontend/src/pages/IndexPage.vue
  swift_browser_ui_frontend/src/pages/LoginPassword.vue
  swift_browser_ui_frontend/src/pages/SelectPage.vue
  swift_browser_ui_frontend/src/views/Folders.vue
  swift_browser_ui_frontend/src/views/Tokens.vue
  swift_browser_ui_frontend/vite.config.js
  vetur.config.js
  volar.config.js
Labels: enhancement, debt

#1041 Fix for selecting and deleting subfolders and files
  .github/config/.finnishwords.txt
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/globalFunctions.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/components/CObjectTable.vue
  swift_browser_ui_frontend/src/components/ContainerTable.vue
  swift_browser_ui_frontend/src/components/DeleteModal.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
Labels: bug, enhancement
