Repository CSCfi/swift-browser-ui, pull requests merged in 2023-01, with the labels that each got.

#871 Bugfix/fixes for data table
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/conv.js
  swift_browser_ui_frontend/src/common/globalFunctions.js
  swift_browser_ui_frontend/src/components/ContainerTable.vue
  swift_browser_ui_frontend/src/components/Containers.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
Labels: bug, enhancement

#912 Update csc-ui library to its latest version
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
Labels: bug, accessibility

#913 missed translations and title
  .github/config/.finnishwords.txt
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/components/ContainerTable.vue
Labels: bug

#851 kill upload sessions on finish
  CHANGELOG.md
  swift_browser_ui/ui/api.py
  swift_browser_ui/ui/server.py
  swift_browser_ui/upload/auth.py
  swift_browser_ui/upload/server.py
  swift_browser_ui_frontend/src/common/api.js
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/common/upload.js
  swift_browser_ui_frontend/src/components/UploadModal.vue
Labels: bug

#916 Feature/accessibility fixes
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/src/components/BrowserSecondaryNavbar.vue
  swift_browser_ui_frontend/src/components/CObjectTable.vue
  swift_browser_ui_frontend/src/components/ContainerTable.vue
  swift_browser_ui_frontend/src/components/CopyFolderModal.vue
  swift_browser_ui_frontend/src/components/CreateFolderModal.vue
  swift_browser_ui_frontend/src/components/EditTagsModal.vue
  swift_browser_ui_frontend/src/components/FolderTabs.vue
  swift_browser_ui_frontend/src/components/ObjectDeleteButton.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
  swift_browser_ui_frontend/src/components/ShareModal.vue
  swift_browser_ui_frontend/src/components/UploadModal.vue
  swift_browser_ui_frontend/src/components/UploadToast.vue
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/pages/IndexOIDCPage.vue
  swift_browser_ui_frontend/src/pages/LoginPassword.vue
Labels: bug, accessibility

#920 Optimize docker image builds for subsequent builds
  CHANGELOG.md
  dockerfiles/Dockerfile-build-crypt
  dockerfiles/Dockerfile-build-crypt-devel
  dockerfiles/Dockerfile-request
  dockerfiles/Dockerfile-runner
  dockerfiles/Dockerfile-sharing
  dockerfiles/Dockerfile-ui
  dockerfiles/Dockerfile-ui-devel
Labels: enhancement

#923 Unify editing tags modal for objects and containers
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/globalFunctions.js
  swift_browser_ui_frontend/src/components/CObjectTable.vue
  swift_browser_ui_frontend/src/components/ContainerTable.vue
  swift_browser_ui_frontend/src/components/CreateFolderModal.vue
  swift_browser_ui_frontend/src/components/EditTagsModal.vue
Labels: debt

#921 Fix 'Copy Share ID' tooltip formatting
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/components/BrowserSecondaryNavbar.vue
Labels: debt
