Repository CSCfi/swift-browser-ui, pull requests merged in 2023-02, with the labels that each got.

#951 Fix hiding the pagination of data tables
  CHANGELOG.md
  swift_browser_ui_frontend/src/components/CObjectTable.vue
  swift_browser_ui_frontend/src/components/ContainerTable.vue
Labels: bug

#954 Fix shared objects functionality
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/store.js
  swift_browser_ui_frontend/src/components/EditTagsModal.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
Labels: bug, debt

#962 Use oidc as default keystone login provider
  .github/config/.env.test
  CHANGELOG.md
  swift_browser_ui/ui/login.py
  swift_browser_ui/ui/server.py
  swift_browser_ui/ui/settings.py
  swift_browser_ui_frontend/src/common/lang.js
Labels: enhancement, debt

#964 Update JS deps, removing deprecated core-js 2.26 dependency
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
Labels: debt

#968 Use new OIDC in OIDC return
  CHANGELOG.md
  swift_browser_ui/ui/login.py
Labels: bug

#967 Make footer stick to bottom in large screens on login pages
  swift_browser_ui_frontend/src/pages/IndexOIDCPage.vue
  swift_browser_ui_frontend/src/pages/IndexPage.vue
  swift_browser_ui_frontend/src/pages/LoginPassword.vue
Labels: debt

#970 Fix missing footer and language-selector component setup
  CHANGELOG.md
  swift_browser_ui_frontend/src/entries/badrequest.js
  swift_browser_ui_frontend/src/entries/forbid.js
  swift_browser_ui_frontend/src/entries/index.js
  swift_browser_ui_frontend/src/entries/index_oidc.js
  swift_browser_ui_frontend/src/entries/loginpassword.js
  swift_browser_ui_frontend/src/entries/notfound.js
  swift_browser_ui_frontend/src/entries/uidown.js
  swift_browser_ui_frontend/src/entries/unauth.js
  swift_browser_ui_frontend/src/pages/IndexOIDCPage.vue
  swift_browser_ui_frontend/src/pages/IndexPage.vue
Labels: bug, debt

#973 Update vue to 2.7.14
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
Labels: debt

#965 Show notification when changing permission in share modal
  .github/config/.finnishwords.txt
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/components/ShareModal.vue
  swift_browser_ui_frontend/src/components/ShareModalTable.vue
Labels: enhancement

#969 Automate building wasm with npm
  .github/workflows/e2etests.yml
  .github/workflows/unit.yml
  CHANGELOG.md
  README.md
  devproxy/Dockerfile-emsdk-deps
  devproxy/README.md
  devproxy/build_wasm.sh
  dockerfiles/Dockerfile-build-crypt
  dockerfiles/Dockerfile-build-crypt-devel
  swift_browser_ui_frontend/build_wasm.sh
  swift_browser_ui_frontend/package.json
Labels: enhancement

#975 Migrate from npm to pnpm
  .github/config/.wordlist.txt
  .github/workflows/e2etests.yml
  .github/workflows/eslint.yml
  .github/workflows/unit.yml
  .github/workflows/vueunit.yml
  Procfile
  README.md
  dockerfiles/Dockerfile-build-crypt
  dockerfiles/Dockerfile-build-crypt-devel
  dockerfiles/Dockerfile-ui
  dockerfiles/Dockerfile-ui-devel
  docs/source/instructions.rst
  docs/source/testing.rst
  swift_browser_ui_frontend/README.md
  swift_browser_ui_frontend/package-lock.json
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/pnpm-lock.yaml
Labels: enhancement

#976 Fix building with dockerfiles
  dockerfiles/Dockerfile-build-crypt-devel
  swift_browser_ui_frontend/build_wasm.sh
  swift_browser_ui_frontend/package.json
Labels: bug, debt

#977 Allow installing js with --prod
  .github/workflows/unit.yml
  CHANGELOG.md
  dockerfiles/Dockerfile-build-crypt
  dockerfiles/Dockerfile-build-crypt-devel
  dockerfiles/Dockerfile-ui
  dockerfiles/Dockerfile-ui-devel
  swift_browser_ui_frontend/package.json
  swift_browser_ui_frontend/pnpm-lock.yaml
Labels: debt

#983 Make elements more semantic and improve accessibility for screen reader users
  .github/config/.finnishwords.txt
  CHANGELOG.md
  swift_browser_ui_frontend/src/common/globalFunctions.js
  swift_browser_ui_frontend/src/common/lang.js
  swift_browser_ui_frontend/src/common/upload.js
  swift_browser_ui_frontend/src/components/BrowserMainNavbar.vue
  swift_browser_ui_frontend/src/components/BrowserSecondaryNavbar.vue
  swift_browser_ui_frontend/src/components/CFooter.vue
  swift_browser_ui_frontend/src/components/ContainerTable.vue
  swift_browser_ui_frontend/src/components/CopyFolderModal.vue
  swift_browser_ui_frontend/src/components/CreateFolderModal.vue
  swift_browser_ui_frontend/src/components/EditTagsModal.vue
  swift_browser_ui_frontend/src/components/FolderTabs.vue
  swift_browser_ui_frontend/src/components/ObjectTable.vue
  swift_browser_ui_frontend/src/components/SearchBox.vue
  swift_browser_ui_frontend/src/components/ShareModal.vue
  swift_browser_ui_frontend/src/components/ShareModalTable.vue
  swift_browser_ui_frontend/src/components/ShareRequestsTable.vue
  swift_browser_ui_frontend/src/components/UploadModal.vue
  swift_browser_ui_frontend/src/pages/BrowserPage.vue
  swift_browser_ui_frontend/src/pages/IndexOIDCPage.vue
  swift_browser_ui_frontend/src/pages/LoginPassword.vue
  swift_browser_ui_frontend/src/pages/SelectPage.vue
  swift_browser_ui_frontend/src/views/Folders.vue
  swift_browser_ui_frontend/src/views/Tokens.vue
Labels: bug, enhancement, accessibility

#988 Changed toggles to checkboxes
  swift_browser_ui_frontend/src/components/UploadModal.vue
Labels: enhancement
